- name: Add dotfiles to global gitignore
  lineinfile:
    path: '{{ ansible_env.HOME }}/.gitignore'
    line: '.dotfiles'
    create: yes

- name: Clone dotfiles
  git:
    repo: 'https://github.com/nayssaj/dotfiles.git'
    dest: '{{ ansible_env.HOME }}/.dotfiles'
    bare: yes

- name: Checkout content
  shell:
    /usr/bin/git --git-dir=$HOME/.dotfiles --work-tree=$HOME checkout

- name: Don't show untracked files
  shell:
    /usr/bin/git --git-dir=$HOME/.dotfiles --work-tree=$HOME config --local status.showUntrackedFiles no
