- name: Add dotfiles to global gitignore
  lineinfile:
    path: '{{ ansible_env.HOME }}/.gitignore'
    line: '.dotfiles'
    create: yes

- name: Create bare dotfile repo
  git:
    repo: 'https://github.com/nayssaj/dotfiles.git'
    dest: '{{ ansible_env.HOME }}/.dotfiles'
    bare: yes

- name: Create backup directory
  file:
    path: '{{ ansible_env.HOME }}/.dotfiles_backup'
    state: directory

- name: Check bashrc existance
  stat:
    path: '{{ ansible_env.HOME }}/.bashrc'
  register: bashrc

- name: Backup old dotfiles
  command: mv {{ansible_env.HOME}}/.bashrc {{ansible_env.HOME/.dotfiles_backup}}
  #    src: '{{ ansible_env.HOME }}/.bashrc'
  #  dest: '{{ ansible_env.HOME }}/.dotfiles_backup'
  when: bashrc.stat.exists

- name: Checkout content
  shell:
    /usr/bin/git --git-dir=$HOME/.dotfiles --work-tree=$HOME checkout

- name: Don't show untracked files
  shell:
    /usr/bin/git --git-dir=$HOME/.dotfiles --work-tree=$HOME config --local status.showUntrackedFiles no
